[package]
name = "MMA"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7", features = ["codec"] }
bytes = "1"
thiserror = "2.0.20"
futures-util = { version = "0.3", features = ["sink"] }
ahash = "0.8.12"

[[example]]
name = "main_server"
path = "examples/main_server.rs"